# Generated by Django 4.2.18 on 2025-01-29 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Право')),
            ],
            options={
                'verbose_name': 'Группа прав',
                'verbose_name_plural': 'Группы прав',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=150, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('course', models.IntegerField(verbose_name='Курс')),
                ('admission_order', models.CharField(max_length=255, verbose_name='Приказ о зачислении')),
                ('transfer_to_2nd_year_order', models.CharField(blank=True, max_length=255, null=True, verbose_name='Приказ о переводе на 2 курс')),
                ('transfer_to_3rd_year_order', models.CharField(blank=True, max_length=255, null=True, verbose_name='Приказ о переводе на 3 курс')),
                ('transfer_to_4th_year_order', models.CharField(blank=True, max_length=255, null=True, verbose_name='Приказ о переводе на 4 курс')),
                ('expelled_due_to_graduation', models.BooleanField(default=False, verbose_name='Отчислен в связи с окончанием обучения')),
                ('education_base', models.CharField(max_length=255, verbose_name='База образования')),
                ('education_basis', models.CharField(max_length=255, verbose_name='Основа образования')),
                ('registration_address', models.TextField(verbose_name='Адрес прописки')),
                ('actual_address', models.TextField(verbose_name='Адрес фактический')),
                ('representative_full_name', models.CharField(max_length=255, verbose_name='ФИО представителя')),
                ('representative_email', models.EmailField(max_length=254, verbose_name='Почта представителя')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('left_course', models.IntegerField(blank=True, null=True, verbose_name='Курс, с которого ушел')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Academhub.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=50, verbose_name='Сокращенное название')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='Academhub.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Квалификация',
                'verbose_name_plural': 'Квалификации',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Право')),
                ('groups', models.ManyToManyField(related_name='permissions', to='Academhub.grouppermission', verbose_name='Группы прав')),
                ('users', models.ManyToManyField(related_name='permissions', to='Academhub.user', verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Право',
                'verbose_name_plural': 'Права',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='Academhub.qualification', verbose_name='Квалификация'),
        ),
        migrations.CreateModel(
            name='Gradebook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='Academhub.discipline', verbose_name='Дисциплина')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='Academhub.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='Academhub.user', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Ведомость',
                'verbose_name_plural': 'Ведомости',
            },
        ),
        migrations.AddField(
            model_name='discipline',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='Academhub.specialty', verbose_name='Специальность'),
        ),
    ]
