# Generated by Django 4.2.18 on 2025-01-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academhub', '0002_alter_student_education_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], verbose_name='Курс'),
        ),
    ]
