# Generated by Django 4.2.18 on 2025-01-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academhub', '0004_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='education_base',
            field=models.CharField(choices=[('9 класс', '9'), ('11 класс', '11')], default='9 класс', max_length=255, verbose_name='База образования'),
        ),
    ]
