# Generated by Django 4.2.18 on 2025-01-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academhub', '0005_alter_student_education_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='education_basis',
            field=models.CharField(choices=[('Бюджеьная основа', 'Бюджет'), ('Внебюджетная основа', 'Внебюджет')], default='Бюджеьная основа', max_length=255, verbose_name='Основа образования'),
        ),
    ]
