# Generated by Django 4.2.18 on 2025-01-21 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QualificationDTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('union_name', models.CharField(max_length=255, verbose_name='Союз Название')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='SpecializationDTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='телефон')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('course', models.IntegerField(verbose_name='курс')),
                ('enrollment_order', models.CharField(max_length=255, verbose_name='приказ о зачислении')),
                ('transfer_to_second_course_order', models.CharField(blank=True, max_length=255, null=True, verbose_name='приказ о переводе на 2 курс')),
                ('transfer_to_third_course_order', models.CharField(blank=True, max_length=255, null=True, verbose_name='приказ о переводе на 3 курс')),
                ('transfer_to_fourth_course_order', models.CharField(blank=True, max_length=255, null=True, verbose_name='приказ о переводе на 4 курс')),
                ('graduation_order', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчислен в связи с окончанием обучения')),
                ('education_base', models.CharField(max_length=255, verbose_name='база образования')),
                ('education_reason', models.CharField(max_length=255, verbose_name='основа образования')),
                ('registration_address', models.CharField(max_length=255, verbose_name='адрес прописка')),
                ('actual_address', models.CharField(max_length=255, verbose_name='адрес фактический')),
                ('representative_name', models.CharField(max_length=255, verbose_name='ФИО представителя')),
                ('representative_email', models.EmailField(max_length=254, verbose_name='почта представителя')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='примечание')),
                ('previous_course', models.IntegerField(blank=True, null=True, verbose_name='курс с которого ушел')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Сontingent.groupdto', verbose_name='группа(FK)')),
            ],
        ),
        migrations.AddField(
            model_name='groupdto',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Сontingent.qualificationdto', verbose_name='Квалификация'),
        ),
        migrations.AddField(
            model_name='groupdto',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Сontingent.specializationdto', verbose_name='специальность (FK)'),
        ),
    ]
