# Generated by Django 4.2.18 on 2025-01-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Сontingent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdto',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
    ]
