# Generated by Django 4.2.18 on 2025-01-21 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Сontingent', '0003_alter_studentdto_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdto',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Сontingent.groupdto', verbose_name='группа(FK)'),
        ),
    ]
