# Generated by Django 4.2.18 on 2025-01-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Сontingent', '0004_alter_studentdto_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationdto',
            name='union_name',
            field=models.CharField(max_length=255, verbose_name='Наименование (сокращение)'),
        ),
    ]
