# Generated by Django 4.2.18 on 2025-01-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Сontingent', '0005_alter_qualificationdto_union_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdto',
            name='group_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер группы'),
        ),
    ]
